/**
 * Source palettes, taken from each theme's published colours (all MIT or similarly licensed;
 * see NOTICE). Only `raw` values live here; semantic tokens and accessibility adjustments are
 * derived in tokens.ts.
 */
export interface RawPalette {
  bg: string; // app background
  surface: string; // sidebar, cards, panels
  surfaceAlt: string; // hover / selected rows
  border: string;
  fg: string;
  muted: string;
  accent: string;
  red: string;
  orange: string;
  yellow: string;
  green: string;
  blue: string;
}

export type Mode = 'light' | 'dark';

export interface VariantDef {
  id: string;
  family: string;
  name: string;
  mode: Mode;
  raw: RawPalette;
}

export interface FamilyDef {
  id: string;
  name: string;
  /** Upstream project, for attribution. */
  homepage: string;
  defaultLight: string;
  defaultDark: string;
}

export const FAMILIES: FamilyDef[] = [
  {
    id: 'bokydo',
    name: 'BokyDo',
    homepage: '',
    defaultLight: 'bokydo-light',
    defaultDark: 'bokydo-dark',
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    homepage: 'https://catppuccin.com',
    defaultLight: 'catppuccin-latte',
    defaultDark: 'catppuccin-mocha',
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    homepage: 'https://github.com/morhetz/gruvbox',
    defaultLight: 'gruvbox-light',
    defaultDark: 'gruvbox-dark',
  },
  {
    id: 'dracula',
    name: 'Dracula',
    homepage: 'https://draculatheme.com',
    defaultLight: 'dracula-alucard',
    defaultDark: 'dracula',
  },
  {
    id: 'nord',
    name: 'Nord',
    homepage: 'https://www.nordtheme.com',
    defaultLight: 'nord-light',
    defaultDark: 'nord',
  },
  {
    id: 'tokyonight',
    name: 'Tokyo Night',
    homepage: 'https://github.com/folke/tokyonight.nvim',
    defaultLight: 'tokyonight-day',
    defaultDark: 'tokyonight-night',
  },
  {
    id: 'solarized',
    name: 'Solarized',
    homepage: 'https://ethanschoonover.com/solarized',
    defaultLight: 'solarized-light',
    defaultDark: 'solarized-dark',
  },
  {
    id: 'one',
    name: 'One Dark / One Light',
    homepage: 'https://github.com/atom/atom',
    defaultLight: 'one-light',
    defaultDark: 'one-dark',
  },
  {
    id: 'rosepine',
    name: 'Rosé Pine',
    homepage: 'https://rosepinetheme.com',
    defaultLight: 'rosepine-dawn',
    defaultDark: 'rosepine',
  },
  {
    id: 'everforest',
    name: 'Everforest',
    homepage: 'https://github.com/sainnhe/everforest',
    defaultLight: 'everforest-light',
    defaultDark: 'everforest-dark',
  },
  {
    id: 'kanagawa',
    name: 'Kanagawa',
    homepage: 'https://github.com/rebelot/kanagawa.nvim',
    defaultLight: 'kanagawa-lotus',
    defaultDark: 'kanagawa-wave',
  },
];

const v = (id: string, family: string, name: string, mode: Mode, raw: RawPalette): VariantDef => ({
  id,
  family,
  name,
  mode,
  raw,
});

export const VARIANTS: VariantDef[] = [
  v('bokydo-light', 'bokydo', 'Light', 'light', {
    bg: '#fafafa',
    surface: '#ffffff',
    surfaceAlt: '#f2f2f2',
    border: '#e5e5e5',
    fg: '#1f1f1f',
    muted: '#666666',
    accent: '#c3392b',
    red: '#d1453b',
    orange: '#eb8909',
    yellow: '#b8860b',
    green: '#058527',
    blue: '#246fe0',
  }),
  v('bokydo-dark', 'bokydo', 'Dark', 'dark', {
    bg: '#141414',
    surface: '#1e1e1e',
    surfaceAlt: '#2a2a2a',
    border: '#333333',
    fg: '#ececec',
    muted: '#a3a3a3',
    accent: '#ef6f5e',
    red: '#ff7066',
    orange: '#ff9a14',
    yellow: '#ffcc33',
    green: '#34c759',
    blue: '#5297ff',
  }),

  v('catppuccin-latte', 'catppuccin', 'Latte', 'light', {
    bg: '#eff1f5',
    surface: '#e6e9ef',
    surfaceAlt: '#dce0e8',
    border: '#ccd0da',
    fg: '#4c4f69',
    muted: '#6c6f85',
    accent: '#8839ef',
    red: '#d20f39',
    orange: '#fe640b',
    yellow: '#df8e1d',
    green: '#40a02b',
    blue: '#1e66f5',
  }),
  v('catppuccin-frappe', 'catppuccin', 'Frappé', 'dark', {
    bg: '#303446',
    surface: '#292c3c',
    surfaceAlt: '#414559',
    border: '#51576d',
    fg: '#c6d0f5',
    muted: '#a5adce',
    accent: '#ca9ee6',
    red: '#e78284',
    orange: '#ef9f76',
    yellow: '#e5c890',
    green: '#a6d189',
    blue: '#8caaee',
  }),
  v('catppuccin-macchiato', 'catppuccin', 'Macchiato', 'dark', {
    bg: '#24273a',
    surface: '#1e2030',
    surfaceAlt: '#363a4f',
    border: '#494d64',
    fg: '#cad3f5',
    muted: '#a5adcb',
    accent: '#c6a0f6',
    red: '#ed8796',
    orange: '#f5a97f',
    yellow: '#eed49f',
    green: '#a6da95',
    blue: '#8aadf4',
  }),
  v('catppuccin-mocha', 'catppuccin', 'Mocha', 'dark', {
    bg: '#1e1e2e',
    surface: '#181825',
    surfaceAlt: '#313244',
    border: '#45475a',
    fg: '#cdd6f4',
    muted: '#a6adc8',
    accent: '#cba6f7',
    red: '#f38ba8',
    orange: '#fab387',
    yellow: '#f9e2af',
    green: '#a6e3a1',
    blue: '#89b4fa',
  }),

  v('gruvbox-light', 'gruvbox', 'Light', 'light', {
    bg: '#fbf1c7',
    surface: '#f2e5bc',
    surfaceAlt: '#ebdbb2',
    border: '#d5c4a1',
    fg: '#3c3836',
    muted: '#665c54',
    accent: '#af3a03',
    red: '#9d0006',
    orange: '#af3a03',
    yellow: '#b57614',
    green: '#79740e',
    blue: '#076678',
  }),
  v('gruvbox-dark', 'gruvbox', 'Dark', 'dark', {
    bg: '#282828',
    surface: '#32302f',
    surfaceAlt: '#3c3836',
    border: '#504945',
    fg: '#ebdbb2',
    muted: '#a89984',
    accent: '#fe8019',
    red: '#fb4934',
    orange: '#fe8019',
    yellow: '#fabd2f',
    green: '#b8bb26',
    blue: '#83a598',
  }),

  v('dracula-alucard', 'dracula', 'Alucard', 'light', {
    bg: '#fffbeb',
    surface: '#f5f1df',
    surfaceAlt: '#ecebd6',
    border: '#cfcfde',
    fg: '#1f1f1f',
    muted: '#6c664b',
    accent: '#644ac9',
    red: '#cb3a2a',
    orange: '#a34d14',
    yellow: '#846e15',
    green: '#14710a',
    blue: '#036a96',
  }),
  v('dracula', 'dracula', 'Dracula', 'dark', {
    bg: '#282a36',
    surface: '#21222c',
    surfaceAlt: '#44475a',
    border: '#44475a',
    fg: '#f8f8f2',
    muted: '#a4acc8',
    accent: '#bd93f9',
    red: '#ff5555',
    orange: '#ffb86c',
    yellow: '#f1fa8c',
    green: '#50fa7b',
    blue: '#8be9fd',
  }),

  v('nord-light', 'nord', 'Snow Storm', 'light', {
    bg: '#eceff4',
    surface: '#e5e9f0',
    surfaceAlt: '#d8dee9',
    border: '#d8dee9',
    fg: '#2e3440',
    muted: '#4c566a',
    accent: '#5e81ac',
    red: '#bf616a',
    orange: '#d08770',
    yellow: '#ebcb8b',
    green: '#a3be8c',
    blue: '#5e81ac',
  }),
  v('nord', 'nord', 'Polar Night', 'dark', {
    bg: '#2e3440',
    surface: '#3b4252',
    surfaceAlt: '#434c5e',
    border: '#4c566a',
    fg: '#eceff4',
    muted: '#d8dee9',
    accent: '#88c0d0',
    red: '#bf616a',
    orange: '#d08770',
    yellow: '#ebcb8b',
    green: '#a3be8c',
    blue: '#81a1c1',
  }),

  v('tokyonight-day', 'tokyonight', 'Day', 'light', {
    bg: '#e1e2e7',
    surface: '#e9e9ed',
    surfaceAlt: '#d0d5e3',
    border: '#c4c8da',
    fg: '#3760bf',
    muted: '#6172b0',
    accent: '#2e7de9',
    red: '#f52a65',
    orange: '#b15c00',
    yellow: '#8c6c3e',
    green: '#587539',
    blue: '#2e7de9',
  }),
  v('tokyonight-night', 'tokyonight', 'Night', 'dark', {
    bg: '#1a1b26',
    surface: '#16161e',
    surfaceAlt: '#292e42',
    border: '#3b4261',
    fg: '#c0caf5',
    muted: '#a9b1d6',
    accent: '#7aa2f7',
    red: '#f7768e',
    orange: '#ff9e64',
    yellow: '#e0af68',
    green: '#9ece6a',
    blue: '#7aa2f7',
  }),
  v('tokyonight-storm', 'tokyonight', 'Storm', 'dark', {
    bg: '#24283b',
    surface: '#1f2335',
    surfaceAlt: '#292e42',
    border: '#3b4261',
    fg: '#c0caf5',
    muted: '#a9b1d6',
    accent: '#7aa2f7',
    red: '#f7768e',
    orange: '#ff9e64',
    yellow: '#e0af68',
    green: '#9ece6a',
    blue: '#7aa2f7',
  }),
  v('tokyonight-moon', 'tokyonight', 'Moon', 'dark', {
    bg: '#222436',
    surface: '#1e2030',
    surfaceAlt: '#2f334d',
    border: '#3b4261',
    fg: '#c8d3f5',
    muted: '#a9b8e8',
    accent: '#82aaff',
    red: '#ff757f',
    orange: '#ff966c',
    yellow: '#ffc777',
    green: '#c3e88d',
    blue: '#82aaff',
  }),

  v('solarized-light', 'solarized', 'Light', 'light', {
    bg: '#fdf6e3',
    surface: '#eee8d5',
    surfaceAlt: '#e6dfc8',
    border: '#d9d2bc',
    fg: '#073642',
    muted: '#586e75',
    accent: '#268bd2',
    red: '#dc322f',
    orange: '#cb4b16',
    yellow: '#b58900',
    green: '#859900',
    blue: '#268bd2',
  }),
  v('solarized-dark', 'solarized', 'Dark', 'dark', {
    bg: '#002b36',
    surface: '#073642',
    surfaceAlt: '#0d4250',
    border: '#174e5c',
    fg: '#eee8d5',
    muted: '#93a1a1',
    accent: '#268bd2',
    red: '#dc322f',
    orange: '#cb4b16',
    yellow: '#b58900',
    green: '#859900',
    blue: '#268bd2',
  }),

  v('one-light', 'one', 'One Light', 'light', {
    bg: '#fafafa',
    surface: '#f0f0f1',
    surfaceAlt: '#e5e5e6',
    border: '#dbdbdc',
    fg: '#383a42',
    muted: '#696c77',
    accent: '#4078f2',
    red: '#e45649',
    orange: '#986801',
    yellow: '#c18401',
    green: '#50a14f',
    blue: '#4078f2',
  }),
  v('one-dark', 'one', 'One Dark', 'dark', {
    bg: '#282c34',
    surface: '#21252b',
    surfaceAlt: '#2c313a',
    border: '#3e4451',
    fg: '#abb2bf',
    muted: '#8b929e',
    accent: '#61afef',
    red: '#e06c75',
    orange: '#d19a66',
    yellow: '#e5c07b',
    green: '#98c379',
    blue: '#61afef',
  }),

  v('rosepine-dawn', 'rosepine', 'Dawn', 'light', {
    bg: '#faf4ed',
    surface: '#fffaf3',
    surfaceAlt: '#f2e9e1',
    border: '#dfdad9',
    fg: '#575279',
    muted: '#797593',
    accent: '#907aa9',
    red: '#b4637a',
    orange: '#d7827e',
    yellow: '#ea9d34',
    green: '#286983',
    blue: '#56949f',
  }),
  v('rosepine', 'rosepine', 'Main', 'dark', {
    bg: '#191724',
    surface: '#1f1d2e',
    surfaceAlt: '#26233a',
    border: '#403d52',
    fg: '#e0def4',
    muted: '#908caa',
    accent: '#c4a7e7',
    red: '#eb6f92',
    orange: '#ebbcba',
    yellow: '#f6c177',
    green: '#31748f',
    blue: '#9ccfd8',
  }),
  v('rosepine-moon', 'rosepine', 'Moon', 'dark', {
    bg: '#232136',
    surface: '#2a273f',
    surfaceAlt: '#393552',
    border: '#44415a',
    fg: '#e0def4',
    muted: '#908caa',
    accent: '#c4a7e7',
    red: '#eb6f92',
    orange: '#ea9a97',
    yellow: '#f6c177',
    green: '#3e8fb0',
    blue: '#9ccfd8',
  }),

  v('everforest-light', 'everforest', 'Light', 'light', {
    bg: '#fdf6e3',
    surface: '#f4f0d9',
    surfaceAlt: '#efebd4',
    border: '#e6e2cc',
    fg: '#5c6a72',
    muted: '#829181',
    accent: '#8da101',
    red: '#f85552',
    orange: '#f57d26',
    yellow: '#dfa000',
    green: '#8da101',
    blue: '#3a94c5',
  }),
  v('everforest-dark', 'everforest', 'Dark', 'dark', {
    bg: '#2d353b',
    surface: '#343f44',
    surfaceAlt: '#3d484d',
    border: '#475258',
    fg: '#d3c6aa',
    muted: '#9da9a0',
    accent: '#a7c080',
    red: '#e67e80',
    orange: '#e69875',
    yellow: '#dbbc7f',
    green: '#a7c080',
    blue: '#7fbbb3',
  }),

  v('kanagawa-lotus', 'kanagawa', 'Lotus', 'light', {
    bg: '#f2ecbc',
    surface: '#e7dba0',
    surfaceAlt: '#e4d794',
    border: '#d5cea3',
    fg: '#545464',
    muted: '#716e61',
    accent: '#624c83',
    red: '#c84053',
    orange: '#cc6d00',
    yellow: '#77713f',
    green: '#6f894e',
    blue: '#4d699b',
  }),
  v('kanagawa-wave', 'kanagawa', 'Wave', 'dark', {
    bg: '#1f1f28',
    surface: '#16161d',
    surfaceAlt: '#2a2a37',
    border: '#363646',
    fg: '#dcd7ba',
    muted: '#a6a69c',
    accent: '#7e9cd8',
    red: '#e46876',
    orange: '#ff9e3b',
    yellow: '#e6c384',
    green: '#98bb6c',
    blue: '#7e9cd8',
  }),
  v('kanagawa-dragon', 'kanagawa', 'Dragon', 'dark', {
    bg: '#181616',
    surface: '#0d0c0c',
    surfaceAlt: '#282727',
    border: '#393836',
    fg: '#c5c9c5',
    muted: '#a6a69c',
    accent: '#8ba4b0',
    red: '#c4746e',
    orange: '#b6927b',
    yellow: '#c4b28a',
    green: '#87a987',
    blue: '#8ba4b0',
  }),
];

/** Todoist-compatible project/label colour names with their base hex values. */
export const PROJECT_COLORS: Record<string, string> = {
  berry_red: '#b8255f',
  red: '#db4035',
  orange: '#ff9933',
  yellow: '#fad000',
  olive_green: '#afb83b',
  lime_green: '#7ecc49',
  green: '#299438',
  mint_green: '#6accbc',
  teal: '#158fad',
  sky_blue: '#14aaf5',
  light_blue: '#96c3eb',
  blue: '#4073ff',
  grape: '#884dff',
  violet: '#af38eb',
  lavender: '#eb96eb',
  magenta: '#e05194',
  salmon: '#ff8d85',
  charcoal: '#808080',
  grey: '#b8b8b8',
  taupe: '#ccac93',
};
