import path from 'node:path';
import { exists, readSecretFile, randomSecret, writeSecretFile } from './secret-files.js';

/**
 * The database password, generated by the app itself on first boot (there is no separate init
 * container). The app keeps its own copy with its other secrets and publishes one more copy into
 * a volume shared only with Postgres, which waits for it before its first start. Postgres never
 * sees `master.key` or `session.key`. Idempotent: existing secrets are never replaced.
 */
export async function ensureDbPassword(secretsDir: string, sharedDir: string): Promise<string> {
  const own = path.join(secretsDir, 'db_password');
  const shared = path.join(sharedDir, 'password');

  // If only the shared copy survived (app volume recreated), adopt it: Postgres already uses it.
  if (!(await exists(own)) && (await exists(shared))) {
    await writeSecretFile(own, await readSecretFile(shared));
  }
  if (!(await exists(own))) {
    try {
      await writeSecretFile(own, randomSecret(32));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'EEXIST') throw err;
    }
  }
  const password = await readSecretFile(own);
  if (!(await exists(shared))) {
    await writeSecretFile(shared, password);
  } else if ((await readSecretFile(shared)) !== password) {
    throw new Error(
      `Database password copies in ${secretsDir} and ${sharedDir} disagree. Restore the matching volume or remove one copy to resync.`,
    );
  }
  return password;
}
