import { lstat, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { beforeEach, describe, expect, it } from 'vitest';
import { ensureDbPassword } from './db-password.js';
import { ensureAppSecrets } from './app-secrets.js';
import { ensureSecretDir, ensureSecretFile, writeSecretFile } from './secret-files.js';

let dir: string;
beforeEach(async () => {
  dir = await mkdtemp(path.join(tmpdir(), 'bokydo-secrets-'));
});

const mode = async (p: string) => (await lstat(p)).mode & 0o777;

describe('secret files', () => {
  it('writes 0400 files inside 0700 dirs', async () => {
    const secrets = path.join(dir, 'secrets');
    await ensureAppSecrets(secrets);
    expect(await mode(secrets)).toBe(0o700);
    expect(await mode(path.join(secrets, 'master.key'))).toBe(0o400);
    expect(await mode(path.join(secrets, 'session.key'))).toBe(0o400);
    expect(await mode(path.join(secrets, 'vapid.key'))).toBe(0o400);
  });

  it('is idempotent and never regenerates keys', async () => {
    const secrets = path.join(dir, 'secrets');
    const a = await ensureAppSecrets(secrets);
    const b = await ensureAppSecrets(secrets);
    expect(a.masterKey.equals(b.masterKey)).toBe(true);
    expect(a.masterKey).toHaveLength(32);
    expect(a.vapidKey.equals(b.vapidKey)).toBe(true);
  });

  it('refuses to overwrite an existing secret', async () => {
    const file = path.join(dir, 's');
    await writeSecretFile(file, 'one');
    await expect(writeSecretFile(file, 'two')).rejects.toMatchObject({ code: 'EEXIST' });
    expect(await readFile(file, 'utf8')).toBe('one');
  });

  it('does not follow a planted symlink', async () => {
    const victim = path.join(dir, 'victim');
    await writeFile(victim, 'original');
    const file = path.join(dir, 'secret');
    await symlink(victim, file);
    await expect(writeSecretFile(file, 'attacker-controlled')).rejects.toMatchObject({
      code: 'EEXIST',
    });
    expect(await readFile(victim, 'utf8')).toBe('original');
  });

  it('survives concurrent first-boot generation', async () => {
    const file = path.join(dir, 'race');
    let n = 0;
    const values = await Promise.all(
      Array.from({ length: 10 }, () => ensureSecretFile(file, () => `v${n++}`)),
    );
    expect(new Set(values).size).toBe(1);
  });

  it('rejects a corrupt master key', async () => {
    const secrets = path.join(dir, 'secrets');
    await ensureSecretDir(secrets);
    await writeSecretFile(path.join(secrets, 'master.key'), 'short');
    await expect(ensureAppSecrets(secrets)).rejects.toThrow(/corrupt/);
  });
});

describe('ensureDbPassword (generated by the app; no init container)', () => {
  const secrets = () => path.join(dir, 'secrets');
  const shared = () => path.join(dir, 'shared');
  const run = async (secretsDir = secrets()) => {
    await ensureSecretDir(secretsDir);
    await ensureSecretDir(shared());
    return ensureDbPassword(secretsDir, shared());
  };

  it('keeps a strong password and publishes a matching 0400 copy for Postgres', async () => {
    const password = await run();
    expect(await readFile(path.join(dir, 'secrets/db_password'), 'utf8')).toBe(password);
    expect(await readFile(path.join(dir, 'shared/password'), 'utf8')).toBe(password);
    expect(Buffer.from(password, 'base64url')).toHaveLength(32);
    expect(await mode(path.join(dir, 'shared/password'))).toBe(0o400);
    expect(await mode(path.join(dir, 'secrets/db_password'))).toBe(0o400);
  });

  it('is idempotent', async () => {
    const first = await run();
    expect(await run()).toBe(first);
  });

  it('publishes the existing password into a new shared volume', async () => {
    const first = await run();
    await rm(shared(), { recursive: true });
    expect(await run()).toBe(first);
    expect(await readFile(path.join(dir, 'shared/password'), 'utf8')).toBe(first);
  });

  it('re-adopts the shared password when the app volume is recreated', async () => {
    const first = await run();
    expect(await run(path.join(dir, 'fresh-secrets'))).toBe(first);
  });

  it('refuses to start when the copies disagree', async () => {
    await run();
    await rm(path.join(dir, 'shared/password'));
    await writeSecretFile(path.join(dir, 'shared/password'), 'something-else');
    await expect(run()).rejects.toThrow(/disagree/);
  });
});
