// Builds the quick-add parser for the Android app (ADR 0016) into its assets. The output is
// committed; CI runs this again and fails if the committed copy differs, so the phone's parser
// can't drift from the web's.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
await build({
  stdin: {
    contents:
      "import { quickAddJson } from './src/bridge.ts';\nglobalThis.bokydoQuickAdd = quickAddJson;\n",
    resolveDir: root,
    sourcefile: 'android-entry.ts',
    loader: 'ts',
  },
  bundle: true,
  format: 'iife',
  minify: true,
  target: 'es2020',
  legalComments: 'none',
  banner: {
    js: '// Generated by `pnpm --filter @bokydo/nlp build:android` from packages/nlp. Do not edit. AGPL-3.0-only.',
  },
  outfile: fileURLToPath(
    new URL('../../../apps/android/app/src/main/assets/nlp.js', import.meta.url),
  ),
  logLevel: 'warning',
});
